"""add specifications column to equipment table

Revision ID: fc78046e07cf
Revises: 194a0f60c826
Create Date: 2026-05-18 12:06:45.570295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc78046e07cf'
down_revision: Union[str, Sequence[str], None] = '194a0f60c826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('specifications', sa.String(length=100), nullable=True))
    op.add_column('equipment', sa.Column('maintenance_interval_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'maintenance_interval_days')
    op.drop_column('equipment', 'specifications')
    # ### end Alembic commands ###
