"""add new table water change logs

Revision ID: c743beef8b3b
Revises: c88279efc450
Create Date: 2026-05-19 20:52:47.044069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c743beef8b3b'
down_revision: Union[str, Sequence[str], None] = 'c88279efc450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aquarium_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('WATER_PARAMETERS', 'POPULATION', 'EQUIPMENT', 'MAINTENANCE', 'ALERT', 'SYSTEM', name='timelineeventtype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aquarium_id'], ['aquariums.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeline_events')
    # ### end Alembic commands ###
