"""create tables Tasks and Equipment

Revision ID: 7f4444a305fc
Revises: 3c934bca14be
Create Date: 2026-05-12 15:36:58.449057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f4444a305fc'
down_revision: Union[str, Sequence[str], None] = '3c934bca14be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aquarium_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('installation_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['aquarium_id'], ['aquariums.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('aquarium_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.Enum('WATER_CHANGE', 'MAINTENANCE', 'TESTS', 'PLANTS', 'CUSTOM', name='tasktype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('repeat_type', sa.Enum('NONE', 'DAILY', 'WEEKLY', 'MONTHLY', name='repeattype'), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aquarium_id'], ['aquariums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_water_tests_aquarium_date', 'water_tests', ['aquarium_id', 'test_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_water_tests_aquarium_date', table_name='water_tests')
    op.drop_table('tasks')
    op.drop_table('equipment')
    # ### end Alembic commands ###
