"""delete cover_image in article_categories

Revision ID: 85b75c102081
Revises: c743beef8b3b
Create Date: 2026-05-20 00:40:13.783633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85b75c102081'
down_revision: Union[str, Sequence[str], None] = 'c743beef8b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('article_categories_image_id_fkey'), 'article_categories', type_='foreignkey')
    op.drop_column('article_categories', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_categories', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('article_categories_image_id_fkey'), 'article_categories', 'images', ['image_id'], ['id'])
    # ### end Alembic commands ###
