"""update db 20.05 14.00 pm

Revision ID: e808e18be322
Revises: df9d0e397381
Create Date: 2026-05-20 14:00:23.846641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e808e18be322'
down_revision: Union[str, Sequence[str], None] = 'df9d0e397381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('image_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('notifications_post_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_constraint(op.f('notifications_actor_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notifications', 'users', ['actor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notifications', 'images', ['image_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'notifications', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_actor_id_fkey'), 'notifications', 'users', ['actor_id'], ['id'])
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('notifications_post_id_fkey'), 'notifications', 'posts', ['post_id'], ['id'])
    op.drop_column('notifications', 'image_id')
    # ### end Alembic commands ###
