"""add new table equipment_logs

Revision ID: 80b485e96567
Revises: fc78046e07cf
Create Date: 2026-05-18 12:17:45.481498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80b485e96567'
down_revision: Union[str, Sequence[str], None] = 'fc78046e07cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_logs',
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('log_type', sa.String(length=100), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment_logs')
    # ### end Alembic commands ###
