"""update db 20.05 13.29 pm

Revision ID: f5e9e43d57b6
Revises: 97131b10bfac
Create Date: 2026-05-20 13:29:39.008527

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f5e9e43d57b6"
down_revision: Union[str, Sequence[str], None] = "97131b10bfac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Сначала удаляем сообщения, потому что они ссылаются на чаты
    op.drop_table("messages")

    # Теперь, когда связей больше нет, спокойно удаляем сами чаты
    op.drop_table("chats")

    # Удаляем лайки комментов и чистим уведомления
    op.drop_table("comment_likes")
    op.drop_constraint(
        op.f("notifications_comment_id_fkey"), "notifications", type_="foreignkey"
    )
    op.drop_column("notifications", "type")
    op.drop_column("notifications", "comment_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notifications",
        sa.Column("comment_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "notifications",
        sa.Column("type", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("notifications_comment_id_fkey"),
        "notifications",
        "comments",
        ["comment_id"],
        ["id"],
    )
    op.create_table(
        "comment_likes",
        sa.Column("comment_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["comment_id"], ["comments.id"], name=op.f("comment_likes_comment_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("comment_likes_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("comment_likes_pkey")),
    )
    op.create_table(
        "messages",
        sa.Column("chat_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("sender_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("text", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("is_read", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"], ["chats.id"], name=op.f("messages_chat_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"], ["users.id"], name=op.f("messages_sender_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("messages_pkey")),
    )
    op.create_table(
        "chats",
        sa.Column("user1_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user2_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user1_id"], ["users.id"], name=op.f("chats_user1_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["user2_id"], ["users.id"], name=op.f("chats_user2_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("chats_pkey")),
    )
    # ### end Alembic commands ###
