"""add new table water change logs

Revision ID: c88279efc450
Revises: 78480333075b
Create Date: 2026-05-18 14:32:17.062720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c88279efc450'
down_revision: Union[str, Sequence[str], None] = '78480333075b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aquarium_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.Enum('PLANNED', 'EMERGENCY', name='changetype'), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.Column('change_date', sa.Date(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aquarium_id'], ['aquariums.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('aquariums', sa.Column('water_change_interval_days', sa.Integer(), server_default='7', nullable=False))
    op.add_column('aquariums', sa.Column('water_change_percentage', sa.Integer(), server_default='30', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aquariums', 'water_change_percentage')
    op.drop_column('aquariums', 'water_change_interval_days')
    op.drop_table('water_change_logs')
    # ### end Alembic commands ###
