"""add reset_code and reset_code_expire to User table

Revision ID: 194a0f60c826
Revises: 7f4444a305fc
Create Date: 2026-05-14 19:00:49.919100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '194a0f60c826'
down_revision: Union[str, Sequence[str], None] = '7f4444a305fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_code', sa.String(length=8), nullable=True))
    op.add_column('users', sa.Column('reset_code_expire', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_code_expire')
    op.drop_column('users', 'reset_code')
    # ### end Alembic commands ###
