"""add column is_approve to Artile

Revision ID: b70629cd5270
Revises: da4f1bf8714b
Create Date: 2026-05-09 00:54:10.389332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b70629cd5270'
down_revision: Union[str, Sequence[str], None] = 'da4f1bf8714b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('is_approved', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'is_approved')
    # ### end Alembic commands ###
