"""Initial migration

Revision ID: f5d68f9a7dfa
Revises: e5bdefb80c07
Create Date: 2026-05-26 21:51:34.170174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5d68f9a7dfa'
down_revision: Union[str, Sequence[str], None] = 'e5bdefb80c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedbacks', 'is_published')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
