"""create Species table

Revision ID: eca4ab069105
Revises: 57e77feb7230
Create Date: 2026-05-12 01:15:51.997336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca4ab069105'
down_revision: Union[str, Sequence[str], None] = '57e77feb7230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species',
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('water_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('scientific_name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('care_level', sa.String(length=50), nullable=False),
    sa.Column('min_volume', sa.Integer(), nullable=False),
    sa.Column('max_size', sa.String(length=50), nullable=False),
    sa.Column('temperature', sa.String(length=50), nullable=True),
    sa.Column('ph', sa.String(length=50), nullable=True),
    sa.Column('lifespan', sa.String(length=50), nullable=True),
    sa.Column('character', sa.String(length=50), nullable=True),
    sa.Column('diet', sa.String(length=50), nullable=True),
    sa.Column('lighting', sa.String(length=50), nullable=True),
    sa.Column('co2', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_species_care_level'), 'species', ['care_level'], unique=False)
    op.create_index(op.f('ix_species_category'), 'species', ['category'], unique=False)
    op.create_index(op.f('ix_species_character'), 'species', ['character'], unique=False)
    op.create_index(op.f('ix_species_diet'), 'species', ['diet'], unique=False)
    op.create_index(op.f('ix_species_min_volume'), 'species', ['min_volume'], unique=False)
    op.create_index(op.f('ix_species_name'), 'species', ['name'], unique=False)
    op.create_index(op.f('ix_species_water_type'), 'species', ['water_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_species_water_type'), table_name='species')
    op.drop_index(op.f('ix_species_name'), table_name='species')
    op.drop_index(op.f('ix_species_min_volume'), table_name='species')
    op.drop_index(op.f('ix_species_diet'), table_name='species')
    op.drop_index(op.f('ix_species_character'), table_name='species')
    op.drop_index(op.f('ix_species_category'), table_name='species')
    op.drop_index(op.f('ix_species_care_level'), table_name='species')
    op.drop_table('species')
    # ### end Alembic commands ###
