"""add table WaterTest

Revision ID: 3c934bca14be
Revises: c2c6a8d4b13b
Create Date: 2026-05-12 13:04:43.124245

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3c934bca14be"
down_revision: Union[str, Sequence[str], None] = "c2c6a8d4b13b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "water_tests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("aquarium_id", sa.Integer(), nullable=False),
        sa.Column("test_date", sa.Date(), nullable=False),
        sa.Column("ph", sa.Float(), nullable=True),
        sa.Column("gh", sa.Float(), nullable=True),
        sa.Column("kh", sa.Float(), nullable=True),
        sa.Column("nh3", sa.Float(), nullable=True),
        sa.Column("no2", sa.Float(), nullable=True),
        sa.Column("no3", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["aquarium_id"], ["aquariums.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("water_tests")
    # ### end Alembic commands ###
