"""delete aquarium_id in post

Revision ID: 5f2eebdb3f8f
Revises: 85b75c102081
Create Date: 2026-05-20 01:55:11.834000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f2eebdb3f8f'
down_revision: Union[str, Sequence[str], None] = '85b75c102081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('posts_aquarium_id_fkey'), 'posts', type_='foreignkey')
    op.drop_column('posts', 'aquarium_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('aquarium_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('posts_aquarium_id_fkey'), 'posts', 'aquariums', ['aquarium_id'], ['id'])
    # ### end Alembic commands ###
