"""update db 20.05 21.37 pm

Revision ID: e5bdefb80c07
Revises: d225203bf86a
Create Date: 2026-05-20 21:37:18.378416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5bdefb80c07'
down_revision: Union[str, Sequence[str], None] = 'd225203bf86a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('new_email_candidate', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email_reset_code', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_reset_code')
    op.drop_column('users', 'new_email_candidate')
    # ### end Alembic commands ###
