"""make article fields nullable

Revision ID: da4f1bf8714b
Revises: 32b9035a433e
Create Date: 2026-05-06 23:00:10.328605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da4f1bf8714b'
down_revision: Union[str, Sequence[str], None] = '32b9035a433e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('articles', 'excerpt',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('articles', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('articles', 'excerpt',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('articles', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
