"""add column type to Species

Revision ID: 7196ad76663e
Revises: eca4ab069105
Create Date: 2026-05-12 01:31:19.966079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7196ad76663e'
down_revision: Union[str, Sequence[str], None] = 'eca4ab069105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('species', sa.Column('type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('species', 'type')
    # ### end Alembic commands ###
